version: "3.3"
services:
  api:
    build: .
    image: operator_api
    container_name: operator_api
    ports:
      - 8015:8015
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks: 
      - model
      - backend
    command: gunicorn -b 0.0.0.0:8015 app:api
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - TRACKING_SERVER=http://138.68.70.41:5000
    depends_on:
      - redis

  celery:
    image: operator_api
    container_name: operator_celery
    volumes:
      - ./app:/app
      - ./app/logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - backend
    command: celery -A tasks worker --loglevel=info --logfile=logs/celery.log -c 2 -n task_worker
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  redis:
    image: redis:6-alpine
    container_name: operator_redis
    networks: 
      - backend
  
  monitor:
    image: operator_api
    container_name: operator_monitor
    volumes:
      - ./app:/app
      - ./app/logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5555:5555
    networks: 
      - backend
      - frontend
    command:  flower -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - api
      - redis

networks:
  model:
    external: true
  backend:
    external: true