version: "3"
services:
  operator:
    container_name: operator
    image: fpcloud/operator-service-adm64:v1.0
    ports:
      - 8015:8015
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  internal:
    name: service_network
    driver: bridge
  host:
    name: host_network
    driver: bridge