version: "3"
services:
  operator-1:
    container_name: operator-1
    image: rkrikbaev/fp-operator:latest
    ports:
      - 8015:8015
    volumes:
      - ./app:/application
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks: 
      - service_network

  operator-2:
    container_name: operator-2
    image: rkrikbaev/fp-operator:latest
    ports:
      - 8016:8015
    volumes:
      - ./app:/application
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
    external: true
