version: "3"
services:
  api:
    build: .
    image: api
    ports:
      - 8015:8015
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks: 
      - service_network
    command: gunicorn -b 0.0.0.0:8000 app:app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    image: api
    volumes:
      - ./app:/app
      - ./app/logs:/app/logs
    command: celery -A tasks worker --loglevel=info  --logfile=logs/celery.log
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  redis:
    image: redis:6-alpine

  monitor:
    image: api
    ports:
      - 5555:5555
    command:  flower -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - api
      - redis

networks:
  service_network:
    driver: bridge
    external: true
