version: "3"
services:
  operator:
    container_name: operator
    image: fpcloud/operator-service:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8015:8001
    volumes:
      # - ./.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  internal:
    name: service_network
    driver: bridge
  host:
    name: host_network
    driver: bridge