docker:
  prophet_model:
    type: 'prophet_model'
    image: 'rkrikbaev/fp-prophet:latest'
    home: /opt/prophet-service
    path_to_env: /Users/rustamkrikbayev/operator
    mlruns: 
    network: 'operator_default'
    limits:
      con_mem_limit: '512m'
      cpuset_cpus: '1'
    features: 'yhat,yhat_lower,yhat_upper,trend'
    port: 8005
    startup: 5
  tensorflow_model:
    image: 'tensorflow/serving:latest'
    network: 'operator_default'
    limits:
      con_mem_limit: '1024m'
      cpuset_cpus: '1'
    features: ''