port: 8005
tracking_server_uri: "http://138.68.70.41:5000"
docker:
  network: 'model'
  prophet:
    image: 'rkrikbaev/fp-prophet:latest'
    network: 'model'
    limits:
      con_mem_limit: '512m'
      cpuset_cpus: '1'
    features: 'yhat,yhat_lower,yhat_upper,trend'
  tensorflow:
    image: 'tensorflow/serving:latest'
    network: 'model'
    limits:
      con_mem_limit: '1024m'
      cpuset_cpus: '1'
