port: 8015
docker:
  prophet:
    image: 'fpcloud/prophet-service:latest'
    limits:
      con_mem_limit: '512m'
      cpuset_cpus: '1'
      network: 'service_network'
  tensorflow:
    image: 'tensorflow/serving:latest'
    limits:
      con_mem_limit: '1024m'
      cpuset_cpus: '1'
      network: 'service_network'     
    