docker:
  prophet:
    image: 'rkrikbaev/fp-prophet:latest'
    network: 'models'
    limits:
      con_mem_limit: '512m'
      cpuset_cpus: '1'
    features: 'yhat,yhat_lower,yhat_upper,trend'
    port: 8005
    startup: 5
  tensorflow:
    image: 'tensorflow/serving:latest'
    network: 'models'
    limits:
      con_mem_limit: '1024m'
      cpuset_cpus: '1'
    features: ''
  test:
    image: alpine:latest
    network: 'operator_model'
    limits:
      con_mem_limit: '512m'
      cpuset_cpus: '1'
    features: ''
