docker:
  prophet_model:
    name: 'prophet_model'
    image: 'rkrikbaev/fp-prophet:latest'
    home: /opt/prophet-service
    mlruns: 
    network: 'operator_default'
    limits:
      con_mem_limit: '512m'
      cpuset_cpus: '1'
    features: 'yhat,yhat_lower,yhat_upper,trend'
    port: 8005
    startup: 5
  tensorflow_model:
    image: 'tensorflow/serving:latest'
    network: 'operator_default'
    limits:
      con_mem_limit: '1024m'
      cpuset_cpus: '1'
    features: ''
  test:
    image: alpine:latest
    network: 'operator_model'
    limits:
      con_mem_limit: '512m'
      cpuset_cpus: '1'
    features: ''
