---
gunicorn:
  bind: 0.0.0.0:8000
  workers: 1
  timeout: 31
prophet:
  host: '0.0.0.0'
  image: 'rkrikbaev/service-prophet:v0.1.1'
  source: '/home/wacs/prophet'
  destination: '/app'
  port: 
    8005/tcp: null
  environment: null
serving:
  host: '0.0.0.0'
  image: 'rkrikbaev/service-prophet:v0.1.1'
  source: '/home/wacs/prophet'
  destination: "/app"
  port: 
    8500/tcp: null
    8501/tcp: null
docker: 
  host: '0.0.0.0'
  port: '8005'
